import { capitalizeString } from '../lib/misc'

// Generated by CodiumAI

describe('capitalizeString', () => {
  // Should capitalize the first letter of a string
  it('should capitalize the first letter of a string', () => {
    const result = capitalizeString('test')
    expect(result).toEqual('Test')
  })

  // Should return the capitalized string
  it('should return the capitalized string', () => {
    const result = capitalizeString('test')
    expect(result).toEqual('Test')
  })

  // Should work with single letter strings
  it('should work with single letter strings', () => {
    const result = capitalizeString('t')
    expect(result).toEqual('T')
  })

  // Should return null if input is null
  it('should return null if input is null', () => {
    const result = capitalizeString(null)
    expect(result).toBeNull()
  })

  // Should return undefined if input is undefined
  it('should return undefined if input is undefined', () => {
    const result = capitalizeString(undefined)
    expect(result).toBeUndefined()
  })
})
